services:
  buzzers:
    build:
      context: .
      args:
        VITE_APP_HOST: ${APP_HOST}

    container_name: qrcode-maker
    restart: unless-stopped

    networks:
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qrcode.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.qrcode.entrypoints=websecure"
      - "traefik.http.routers.qrcode.tls.certresolver=letsencrypt"
      # - "traefik.http.services.qrcode.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
